# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

env:
  - GO111MODULE=on
  - CGO_ENABLED=0

before:
  hooks:
    - ./scripts/manpages.sh
    - ./scripts/completions.sh

builds:
  - id: bitswan-gitops-cli
    binary: bitswan-gitops-cli
    ldflags:
      - -s -w
      - -X main.version={{ .Version }}
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    mod_timestamp: '{{ .CommitTimestamp }}'

archives:
  - id: bitswan-gitops-cli
    builds:
      - bitswan-gitops-cli
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE*
      - completions/*
      - manpages/*

nfpms:
  - id: bitswan-gitops-cli
    package_name: bitswan-gitops-cli
    builds:
      - bitswan-gitops-cli
    vendor: bitswan-space
    homepage: https://github.com/bitswan-space/bitswan-workspaces
    maintainer: "LibertyAces Ltd. <support@libertyaces.com>"
    description: "A general purpose golang CLI template for Github and Gitlab"
    license: BSD
    bindir: /usr/bin
    contents:
      - src: ./manpages/bitswan-gitops-cli.1.gz
        dst: /usr/share/man/man1/bitswan-gitops-cli.1.gz
        file_info:
          mode: 0644
      - src: ./completions/bitswan-gitops-cli.bash
        dst: /usr/share/bash-completion/completions/bitswan-gitops-cli
        file_info:
          mode: 0644
      - src: ./completions/bitswan-gitops-cli.fish
        dst: /usr/share/fish/vendor_completions.d/bitswan-gitops-cli.fish
        file_info:
          mode: 0644
      - src: ./completions/bitswan-gitops-cli.zsh
        dst: /usr/share/zsh/vendor-completions/_bitswan-gitops-cli
        file_info:
          mode: 0644

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^test:'
      - '^chore'
      - 'merge conflict'
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
      - go mod tidy
  groups:
    - title: Dependency updates
      regexp: '^.*?(feat|fix)\(deps\)!?:.+$'
      order: 300
    - title: 'New Features'
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 100
    - title: 'Bug fixes'
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 200
    - title: 'Documentation updates'
      regexp: ^.*?doc(\([[:word:]]+\))??!?:.+$
      order: 400
    - title: Other work
      order: 9999

release:
  github:
    owner: bitswan-space
    name: bitswan-workspaces
  draft: false
  prerelease: auto
  mode: replace
  header: |
    ## BitSwan GitOps CLI ({{ .Version }})

    For more information, please see the [documentation](https://github.com/bitswan-space/bitswan-workspaces/blob/main/README.md).
