FROM golang:1.24-bookworm AS builder

WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -ldflags="-s -w" -o /container-manager ./cmd/containermanager

FROM scratch
COPY --from=builder /container-manager /container-manager
ENTRYPOINT ["/container-manager"]
