name: Goreleaser CalVer Release Workflow

on:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write

jobs:
  build-and-release:
    name: Build and Release with Goreleaser CalVer
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21

      - name: Generate CalVer version
        id: calver
        run: |
          # Get current date in YYYY.MM.DD format
          DATE_VERSION=$(date +%Y.%m.%d)
          # Get GitHub run number
          BUILD_NUMBER=${{ github.run_number }}
          # Combine for final version
          CALVER_VERSION="${DATE_VERSION}.${BUILD_NUMBER}"
          echo "version=${CALVER_VERSION}" >> $GITHUB_OUTPUT
          echo "Generated CalVer version: ${CALVER_VERSION}"

      - name: Create Git tag
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git tag "v${{ steps.calver.outputs.version}}"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

